{% set version = '0.9-69-3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rvaidememoire
  version: {{ version|replace("-", "_") }}

source:
  fn: RVAideMemoire_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/RVAideMemoire_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RVAideMemoire/RVAideMemoire_{{ version }}.tar.gz
  sha256: 41ce38ae568a618d7ec6c0182fad02d35092d943d9d7bb07988859096070a4a2

build:
  merge_build_host: True  # [win]
  number: 0
  # r-mixomics not available on OSX due to r-rgl.
  skip: true  # [win32 or osx]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-factominer
    - r-mass
    - r-ade4 >=1.7_8
    - r-boot
    - r-car
    - r-cramer
    - r-dunn.test
    - r-lme4 >=1.0_4
    - r-mixomics >=5.0.2
    - r-multcompview
    - r-nnet
    - r-pls
    - r-pspearman
    - r-vegan >=2.4_3
  run:
    - r-base
    - r-factominer
    - r-mass
    - r-ade4 >=1.7_8
    - r-boot
    - r-car
    - r-cramer
    - r-dunn.test
    - r-lme4 >=1.0_4
    - r-mixomics >=5.0.2
    - r-multcompview
    - r-nnet
    - r-pls
    - r-pspearman
    - r-vegan >=2.4_3

test:
  commands:
    - $R -e "library('RVAideMemoire')"           # [not win]
    - "\"%R%\" -e \"library('RVAideMemoire')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=RVAideMemoire
  license: GPL-2
  summary: Contains miscellaneous functions useful in biostatistics, mostly univariate and multivariate
    testing procedures with a special emphasis on permutation tests. Many functions
    intend to simplify user's life by shortening existing procedures or by implementing
    plotting functions that can be used with as many methods from different packages
    as possible.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-2'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
