{% set version = '0.9-73' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rvaidememoire
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RVAideMemoire_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RVAideMemoire/RVAideMemoire_{{ version }}.tar.gz
  sha256: 0f86c757385dc000ba1761097e2621bdd8a73ddafd0f6beaecf67ec61ade5bfe

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-factominer
    - r-mass
    - r-ade4 >=1.7_8
    - r-boot
    - r-car
    - r-cramer
    - r-lme4 >=1.0_4
    - r-mixomics
    - r-nnet
    - r-pls
    - r-pspearman
    - r-vegan >=2.4_3
  run:
    - r-base
    - r-factominer
    - r-mass
    - r-ade4 >=1.7_8
    - r-boot
    - r-car
    - r-cramer
    - r-lme4 >=1.0_4
    - r-mixomics
    - r-nnet
    - r-pls
    - r-pspearman
    - r-vegan >=2.4_3

test:
  commands:
    - $R -e "library('RVAideMemoire')"           # [not win]
    - "\"%R%\" -e \"library('RVAideMemoire')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=RVAideMemoire
  license: GPL-2
  summary: Contains miscellaneous functions useful in biostatistics, mostly univariate and multivariate
    testing procedures with a special emphasis on permutation tests. Many functions
    intend to simplify user's life by shortening existing procedures or by implementing
    plotting functions that can be used with as many methods from different packages
    as possible.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Encoding: latin1
# Package: RVAideMemoire
# Type: Package
# Title: Testing and Plotting Procedures for Biostatistics
# Version: 0.9-73
# Date: 2019-03-26
# Author: Maxime Herve
# Maintainer: Maxime Herve <maxime.herve@univ-rennes1.fr>
# Imports: ade4 (>= 1.7-8), boot, car, cramer, FactoMineR, graphics, grDevices, lme4 (>= 1.0-4), MASS, mixOmics, nnet, pls, pspearman, stats, utils, vegan (>= 2.4-3)
# Suggests: dgof, emmeans, ordinal, survival
# Description: Contains miscellaneous functions useful in biostatistics, mostly univariate and multivariate testing procedures with a special emphasis on permutation tests. Many functions intend to simplify user's life by shortening existing procedures or by implementing plotting functions that can be used with as many methods from different packages as possible.
# License: GPL-2
# LazyLoad: yes
# NeedsCompilation: no
# Packaged: 2019-03-26 08:08:18 UTC; maherve
# Repository: CRAN
# Date/Publication: 2019-03-26 09:06:10 UTC
