travis:
  secure:
    BINSTAR_TOKEN: A2C7msvbdN5Ck0bDhNAbRxytHZ3P96aWVqQ4f0sLZ/w7IImqojKG3YWRIKOXnXOG8jVkvbMdQKt/NDpWu4bP27yQ2aXiZnRCz6SpX0kgaF6GTE3LmTB8/eAOKb81c9ttfPuSJL3KnDHdgM0Mq4V/JBa34W2Q1dXeGrKG0RS+Z9VkR0JuhUTXKn3BKJEj+chUhv1g4hRuSloOo4WXLaN96XJTcCF14+Ikulup1wyFa0kRChbylQ6elHVnAQs5bus7EEz46sC/N7vV5AcZ2ArMtSNVYOnBMxzyVd+xCGBsPx5DgZr0ElvDRQ1DkP0NgPRCBbtPuTKnhXZ49tnpeAzD+tNjI0j+gTEi8U6kev2XgEswC7ttpJUZ60xsTVowlbOEGlK099kxBvYWzHWnHPJ8UpJhA2Nw/kQtMaT8yTeIBJk2ICdzmQrre7zo7KPvBBlTehQFF2PCWQXRbB7dusQKS7TLqxet/HrToYDvBQS70sxmiuMOWivOT2ndKuvoccA7W5LCgJ1HtYXwJRdHjbya581jWq4AWiWvkODIk7Ln76VErIelKrmbwe6Zxxd/S0y9hckpQBcRzA3oHa/3Ijod06nmSo1eWjoiWcwe24oHQHNkn3A79ZaRpIRGAMw7tlgNZ77vmMv4dn06WenMeo6fZksB4Rh7Ok8dkLljV2j73fw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
