appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: HmFNqOw0tzwXlyPkxCDf4zUxcVtMYgrCEorWoLNl3RIVjrsQmZVn6naZhVkVCF+v2xoczfBb2TUA3g8s611rRUQ9wBdIPBxDuy2gEg0xFDJX08RA8SOqY/aO5nINtYYtdbl97UD84Bh7idqYPzALP+odt0klFbKeAtGf0Uqogu6r64Serl8VAan43cMPhOs564pfK3E1+1ohICEKcB0YkhB0ucr8G4JAP0FcRPBMyLox0EJI5rzwXFPhUWKdHMpUBWvz5vibtmDNnGKFBOP4qOreTvgx3ikDq3SmO4dPgIG5i6aSToQ3jqMttCcg2sgpyLWZSJzoxDVhEH1b/icQmfJGKbnMVCHKG1aaKBTynr6T2rO919kZ3zzURbIWoHuFLi8TmJq09GYO2qjim/0CkXUHdPD+Xjt3kWTQjfqzG68VQH7P5Pw0PRGC8eCMOZbsVu/SPDHVOAQyYKLG2dik8aLqhVXiJlmHurPIq1Uu8ZEM0FNN/cL1EcRzWXq27sxuV2paSbCOj+B+VmXn+oPnFi6OJZsTYzAMEWgjPaF9A8V5Oiye5dlFpy8p7hHaTRsntKPH0xkaABBSa7wCtZZL5IhzfjbICqml6RCMI/blwFIxygft+ifqycYoZiJrz2MKLtCAG2s+swJcvo7aBxYsf/hF8bTOHRIkot5YfZjsDXI=}
bot:
  automerge: true
